#
# Skeleton file for the Python "Bob" exercise.
#
def hey(what):
	if what.isspace() or len(what) == 0:	  #if he isn't told anything...
		return 'Fine. Be that way!'
	elif what.isupper():			  #If he is being shouted at...
		return "Whoa, chill out!"
	elif what.endswith('?'):  #if he is asked a question...
		return 'Sure.'
	else:
		return "Whatever."		#And if all else fails, then...
