def numeral(arab):
    roman = ""
    while arab >= 1000:
        roman += 'M'
        arab -= 1000
    if arab >= 900:
        roman += 'CM'
        arab -= 900
    if arab >= 500:
        roman += 'D'
        arab -= 500
    if arab >= 400:
        roman += 'CD'
        arab -= 400
    while arab >= 100:
        roman += 'C'
        arab -= 100
    if arab >= 90:
        roman += 'XC'
        arab -= 90
    if arab >= 50:
        roman += 'L'
        arab -= 50
    if arab >= 40:
        roman += 'XL'
        arab -= 40
    while arab >= 10:
        roman += 'X'
        arab -= 10
    if arab >= 9:
        roman += 'IX'
        arab -= 9
    if arab >= 5:
        roman += 'V'
        arab -= 5
    if arab >= 4:
        roman += 'IV'
        arab -= 4
    while arab >= 1:
        roman += 'I'
        arab -= 1
    return roman
