import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;

/**
 * Implements the commit class used in CommitTree and Gitlet Encapsulates the
 * critical features of a commit
 * 
 * @authors Nikat Patel 	cs61bl-do
 * 			Rowan Sandhu 	cs61bl-de
 * 			Ryan Panwar 	cs61bl-dk
 *          Shaswat Shah 	cs61bl-mj
 */

public class Commit implements Serializable {

	///////////////////////////////////////////////////////////////
	/********************** Commit Object ************************/
	///////////////////////////////////////////////////////////////

	/**
	 * All variables are final since a commit is final and can not be changed
	 * tracking contains a key-value pair of file path relative to current
	 * directory and the location where its snapshot is stored including in
	 * previous commits
	*/
	private final HashMap<String, String> tracking;
	private final int id;
	private final String message;
	private final Date timeOfCommit;
	private final Commit parent;

	/**
	 * Constructor for the commit class
	 * Commit id and time generated by constructor
	 * 
	 * @param tracking
	 *            HashMap with file, path of backup pairs for files tracked by
	 *            this commit
	 * @param parent
	 *            Parent commit of this commit
	 * @param message
	 *            Commit message of this commit
	 */
	public Commit(HashMap<String, String> tracking, Commit parent, String message, int id) {
		this.tracking = tracking;
		this.message = message;
		this.timeOfCommit = new Date();
		this.id = id;
		this.parent = parent;
	}

	/**
	 * Getter method for commit tracking list
	 * 
	 * @return HashMap with file, path of snapshot for files tracked by this
	 *         commit
	 */
	public HashMap<String, String> getTracking() {
		return tracking;
	}

	/**
	 * Getter method for commit message
	 * 
	 * @return commit message
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * Getter method for commit time
	 * 
	 * @return commit time in comparable format
	 */
	public Date getTime() {
		return timeOfCommit;
	}

	/**
	 * Getter method for commit time
	 * 
	 * @return commit time in string output format
	 */
	public String getTimeString() {
		SimpleDateFormat time = new SimpleDateFormat("yyyy-MM-dd' 'HH:mm:ss");
		return time.format(timeOfCommit);
	}

	/**
	 * Getter method for commit id
	 * 
	 * @return commit id
	 */
	public int getId() {
		return id;
	}

	/**
	 * Getter method for commit parent
	 * 
	 * @return parent of commit
	 */
	public Commit getParent() {
		return parent;
	}
}