"""
Defines an object that represents a strand of DNA.
A strand of DNA is a string containing any number of
adenine (A), cytosine (C), guanine (G), and thymine (T)
nucleotides.
"""


class DNA(object):
    """
    Represents a DNA strand.

    Can be converted to RNA via the to_rna() method.
    """

    def __init__(self, dna=None):
        self.dna = dna

    def to_rna(self):
        """
        Returns an RNA strand based on the DNA strand.

        RNA is generated by replacing Thymine (T) with Uracil (U)
        """
        return self.dna.replace("T", "U")
