def slices(numstr, n):
    """Generate a list of integer lists by slicing the given number string. 
    
    Args:
        numstr (str): a string of numbers.
        n: the number of characters sliced out from the string at once. 
        
    Returns:
        A list of integer lists generated by slicing n characters 
        from the numstr sequentially.
    
    Raises:
        ValueError: if n is not a meaningful number.
    """
    
    n_char =  len(numstr)
    
    if (n <= 0) or (n > n_char):
        raise ValueError() 
    
    return [[int(j) for j in numstr[i:i+n]] for i in range(n_char-n+1)]
