class Gigasecond
  GIGASECOND = 10**9
  SECONDS_IN_A_MINUTE = 60 
  MINUTES_IN_AN_HOUR = 60
  HOURS_IN_A_DAY = 24
  SECONDS_IN_A_DAY = SECONDS_IN_A_MINUTE * MINUTES_IN_AN_HOUR * HOURS_IN_A_DAY
  DAYS_IN_GIGASECOND = GIGASECOND / SECONDS_IN_A_DAY

  def self.from start_date
    start_date + DAYS_IN_GIGASECOND
  end

end
